In [10]:
from CybORG import CybORG
from CybORG.Simulator.Scenarios import EnterpriseScenarioGenerator
from CybORG.Agents.Wrappers import BlueFixedActionWrapper
from rich import print
import numpy as np

In [12]:
sg = EnterpriseScenarioGenerator()
cyborg = CybORG(scenario_generator=sg)

env = BlueFixedActionWrapper(env=cyborg)
obs, _ = env.reset()

print(obs.keys())

dict_keys(['blue_agent_0', 'blue_agent_1', 'blue_agent_2', 'blue_agent_3', 'blue_agent_4'])

In [13]:
print(obs['blue_agent_0'])

{
    'success': <TernaryEnum.UNKNOWN: 2>,
    'restricted_zone_a_subnet_router': {
        'Interface': [
            {
                'interface_name': 'eth0',
                'ip_address': IPv4Address('10.0.137.190'),
                'Subnet': IPv4Network('10.0.137.0/24')
            }
        ],
        'Sessions': [
            {
                'session_id': 0,
                'username': 'ubuntu',
                'timeout': 0,
                'PID': 7,
                'Type': <SessionType.VELOCIRAPTOR_SERVER: 8>,
                'agent': 'blue_agent_0'
            }
        ],
        'Processes': [{'PID': 7, 'username': 'ubuntu'}],
        'User Info': [{'username': 'root', 'Groups': [{'GID': 0}]}, {'username': 'user', 'Groups': [{'GID': 1}]}],
        'System info': {
            'Hostname': 'restricted_zone_a_subnet_router',
            'OSType': <OperatingSystemType.LINUX: 3>,
            'OSDistribution': <OperatingSystemDistribution.KALI: 9>,
            'OSVersion': <OperatingSystemVersion.K2019_4: 11>,
            'Architecture': <Architecture.x64: 2>,
            'position': array([0., 0.])
        }
    },
    'restricted_zone_a_subnet_user_host_0': {
        'Interface': [
            {
                'interface_name': 'eth0',
                'ip_address': IPv4Address('10.0.137.146'),
                'Subnet': IPv4Network('10.0.137.0/24')
            }
        ],
        'Sessions': [
            {
                'session_id': 1,
                'username': 'ubuntu',
                'timeout': 0,
                'PID': 7720,
                'Type': <SessionType.UNKNOWN: 1>,
                'agent': 'blue_agent_0'
            }
        ],
        'Processes': [{'PID': 7720, 'username': 'ubuntu'}],
        'User Info': [{'username': 'root', 'Groups': [{'GID': 0}]}, {'username': 'user', 'Groups': [{'GID': 1}]}],
        'System info': {
            'Hostname': 'restricted_zone_a_subnet_user_host_0',
            'OSType': <OperatingSystemType.LINUX: 3>,
            'OSDistribution': <OperatingSystemDistribution.KALI: 9>,
            'OSVersion': <OperatingSystemVersion.K2019_4: 11>,
            'Architecture': <Architecture.x64: 2>,
            'position': array([0., 0.])
        }
    },
    'restricted_zone_a_subnet_user_host_1': {
        'Interface': [
            {
                'interface_name': 'eth0',
                'ip_address': IPv4Address('10.0.137.102'),
                'Subnet': IPv4Network('10.0.137.0/24')
            }
        ],
        'Sessions': [
            {
                'session_id': 2,
                'username': 'ubuntu',
                'timeout': 0,
                'PID': 8513,
                'Type': <SessionType.UNKNOWN: 1>,
                'agent': 'blue_agent_0'
            }
        ],
        'Processes': [{'PID': 8513, 'username': 'ubuntu'}],
        'User Info': [{'username': 'root', 'Groups': [{'GID': 0}]}, {'username': 'user', 'Groups': [{'GID': 1}]}],
        'System info': {
            'Hostname': 'restricted_zone_a_subnet_user_host_1',
            'OSType': <OperatingSystemType.LINUX: 3>,
            'OSDistribution': <OperatingSystemDistribution.KALI: 9>,
            'OSVersion': <OperatingSystemVersion.K2019_4: 11>,
            'Architecture': <Architecture.x64: 2>,
            'position': array([0., 0.])
        }
    },
    'restricted_zone_a_subnet_user_host_2': {
        'Interface': [
            {
                'interface_name': 'eth0',
                'ip_address': IPv4Address('10.0.137.123'),
                'Subnet': IPv4Network('10.0.137.0/24')
            }
        ],
        'Sessions': [
            {
                'session_id': 3,
                'username': 'ubuntu',
                'timeout': 0,
                'PID': 5561,
                'Type': <SessionType.UNKNOWN: 1>,
                'agent': 'blue_agent_0'
            }
        ],
        'Processes': [{'PID': 5561, 'username': 'ubuntu'}],
        'User Info': [{'username': 'root', 'Gro

In [14]:
print(env.action_space('blue_agent_0'))
print(env.action_labels('blue_agent_0'))

Discrete(82)

[
    'Analyse restricted_zone_a_subnet_server_host_0',
    'Analyse restricted_zone_a_subnet_server_host_1',
    'Analyse restricted_zone_a_subnet_server_host_2',
    'Analyse restricted_zone_a_subnet_server_host_3',
    'Analyse restricted_zone_a_subnet_server_host_4',
    '[Invalid] Analyse restricted_zone_a_subnet_server_host_5',
    'Analyse restricted_zone_a_subnet_user_host_0',
    'Analyse restricted_zone_a_subnet_user_host_1',
    'Analyse restricted_zone_a_subnet_user_host_2',
    '[Invalid] Analyse restricted_zone_a_subnet_user_host_3',
    '[Invalid] Analyse restricted_zone_a_subnet_user_host_4',
    '[Invalid] Analyse restricted_zone_a_subnet_user_host_5',
    '[Invalid] Analyse restricted_zone_a_subnet_user_host_6',
    '[Invalid] Analyse restricted_zone_a_subnet_user_host_7',
    '[Invalid] Analyse restricted_zone_a_subnet_user_host_8',
    '[Invalid] Analyse restricted_zone_a_subnet_user_host_9',
    'Monitor',
    'Remove restricted_zone_a_subnet_server_host_0',
    'Remove restricted_zone_a_subnet_server_host_1',
    'Remove restricted_zone_a_subnet_server_host_2',
    'Remove restricted_zone_a_subnet_server_host_3',
    'Remove restricted_zone_a_subnet_server_host_4',
    '[Invalid] Remove restricted_zone_a_subnet_server_host_5',
    'Remove restricted_zone_a_subnet_user_host_0',
    'Remove restricted_zone_a_subnet_user_host_1',
    'Remove restricted_zone_a_subnet_user_host_2',
    '[Invalid] Remove restricted_zone_a_subnet_user_host_3',
    '[Invalid] Remove restricted_zone_a_subnet_user_host_4',
    '[Invalid] Remove restricted_zone_a_subnet_user_host_5',
    '[Invalid] Remove restricted_zone_a_subnet_user_host_6',
    '[Invalid] Remove restricted_zone_a_subnet_user_host_7',
    '[Invalid] Remove restricted_zone_a_subnet_user_host_8',
    '[Invalid] Remove restricted_zone_a_subnet_user_host_9',
    'Restore restricted_zone_a_subnet_server_host_0',
    'Restore restricted_zone_a_subnet_server_host_1',
    'Restore restricted_zone_a_subnet_server_host_2',
    'Restore restricted_zone_a_subnet_server_host_3',
    'Restore restricted_zone_a_subnet_server_host_4',
    '[Invalid] Restore restricted_zone_a_subnet_server_host_5',
    'Restore restricted_zone_a_subnet_user_host_0',
    'Restore restricted_zone_a_subnet_user_host_1',
    'Restore restricted_zone_a_subnet_user_host_2',
    '[Invalid] Restore restricted_zone_a_subnet_user_host_3',
    '[Invalid] Restore restricted_zone_a_subnet_user_host_4',
    '[Invalid] Restore restricted_zone_a_subnet_user_host_5',
    '[Invalid] Restore restricted_zone_a_subnet_user_host_6',
    '[Invalid] Restore restricted_zone_a_subnet_user_host_7',
    '[Invalid] Restore restricted_zone_a_subnet_user_host_8',
    '[Invalid] Restore restricted_zone_a_subnet_user_host_9',
    'Sleep',
    'AllowTrafficZone restricted_zone_a_subnet (10.0.137.0/24) <- admin_network_subnet (10.0.26.0/24)',
    'AllowTrafficZone restricted_zone_a_subnet (10.0.137.0/24) <- contractor_network_subnet (10.0.199.0/24)',
    'AllowTrafficZone restricted_zone_a_subnet (10.0.137.0/24) <- internet_subnet (10.0.24.0/24)',
    'AllowTrafficZone restricted_zone_a_subnet (10.0.137.0/24) <- office_network_subnet (10.0.16.0/24)',
    'AllowTrafficZone restricted_zone_a_subnet (10.0.137.0/24) <- operational_zone_a_subnet (10.0.164.0/24)',
    'AllowTrafficZone restricted_zone_a_subnet (10.0.137.0/24) <- operational_zone_b_subnet (10.0.112.0/24)',
    'AllowTrafficZone restricted_zone_a_subnet (10.0.137.0/24) <- public_access_zone_subnet (10.0.13.0/24)',
    'AllowTrafficZone restricted_zone_a_subnet (10.0.137.0/24) <- restricted_zone_b_subnet (10.0.63.0/24)',
    'BlockTrafficZone restricted_zone_a_subnet (10.0.137.0/24) <- admin_network_subnet (10.0.26.0/24)',
    'BlockTrafficZone restricted_zone_a_subnet (10.0.137.0/24) <- contractor_network_subnet (10.0.199.0/24)',
    'BlockTrafficZone restricted_zone_a_subnet (10.0.137.0/24) <- internet_subnet (10.0.24.0/24)',
    'BlockTrafficZone restricted_zone_a_subnet

In [16]:
actions = {'blue_agent_0': 42}
obs, reward, terminated, truncated, info = env.step(actions)
print(reward['blue_agent_0'])

0

In [17]:
messages = {'blue_agent_0': np.array([1, 0, 0, 0, 0, 0, 0, 0])}
obs, reward, terminated, truncated, info = env.step(actions, messages=messages)
print(obs['blue_agent_1']['message'])

[
    array([ True, False, False, False, False, False, False, False]),
    array([False, False, False, False, False, False, False, False]),
    array([False, False, False, False, False, False, False, False]),
    array([False, False, False, False, False, False, False, False])
]

In [18]:
from CybORG.Agents.Wrappers import BlueFlatWrapper

env = BlueFlatWrapper(env=cyborg)
obs, _ = env.reset()

print('Space: ', env.observation_space('blue_agent_0'), '\n')
print('Observation: ', obs['blue_agent_0'])

Space:  MultiDiscrete([3 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2])

Observation:  [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]